version: '3.8'

services:
  backend:
    build:
      context: ./backend
    environment:
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - OPENAI_KEY=${OPENAI_KEY}
      - PORT=5000
    ports:
      - 5000:5000
