version: '3.8'

services:
  backend:
    build:
      context: ./backend
    environment:
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - OPENAI_KEY=${OPENAI_KEY}
      - PORT=5000
    ports:
      - 5000:5000

  frontend:
    build: .
    command: npm run dev
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:5000
    ports:
      - 3000:3000
    depends_on:
      - backend
