name: Cypress E2E on PR
on:
  pull_request:
  workflow_dispatch:
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout frontend repo
        uses: actions/checkout@v3
        
      - name: Checkout backend repo
        uses: actions/checkout@v3
        with:
          repository: fac-31/Pro0428-MindPalaceBackend
          path: backend
          
      - name: Generate backend .env file
        run: |
          cd backend
          echo OPENAI_KEY=${{ secrets.OPENAI_KEY }} >> .env
          echo SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }} >> .env
          echo PORT=5000 >> .env
          
      - name: Start backend
        run: |
          cd backend
          docker compose up -d
          
      - name: Debug - Check running containers and ports
        run: |
          echo "=== Docker containers ==="
          docker ps
          echo "=== Port mappings ==="
          docker port $(docker ps -q)
          echo "=== Network listening ==="
          netstat -tlnp

      - name: Wait for backend to be ready
        run: |
          for i in {1..10}; do
            echo "Attempt $i: checking backend..."
            if curl -f http://localhost:5000; then
              echo "Backend is ready"
              exit 0
            fi
            sleep 3
          done
          echo "Backend failed to start"
          exit 1

      - name: Install frontend dependencies
        run: npm ci
        
      - name: Install wait-on
        run: npm install -g wait-on
        
      - name: Build frontend (for Next.js)
        run: npm run build
        
      - name: Start frontend server in development mode
        run: npm run dev &
        
      - name: Wait for frontend to be ready  
        run: |
          echo "Waiting for frontend..."
          wait-on http://localhost:3000 --timeout 60000 --interval 2000 --verbose
        
      - name: Run Cypress tests
        run: npx cypress run
        env:
          CYPRESS_baseUrl: http://localhost:3000
