name: Cypress E2E on PR

on:
  pull_request:
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout frontend repo
        uses: actions/checkout@v3
        
      - name: Checkout backend repo
        uses: actions/checkout@v3
        with:
          repository: fac-31/Pro0428-MindPalaceBackend
          path: backend
          
      - name: Build frontend dependencies
        run: npm ci

      - name: Build & start full stack using docker-compose
        run: docker compose -f docker-compose.ci.yml up -d --build
        env:
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}

      - name: Wait for backend to be ready
        run: |
          for i in {1..10}; do
            if curl -f http://localhost:5000; then
              echo "Backend is up"
              exit 0
            fi
            echo "Waiting for backend..."
            sleep 3
          done
          exit 1

      - name: Wait for frontend to be ready
        run: |
          for i in {1..10}; do
            if curl -f http://localhost:3000; then
              echo "Frontend is up"
              exit 0
            fi
            echo "Waiting for frontend..."
            sleep 3
          done
          exit 1

      - name: Run Cypress tests
        run: npx cypress run
        env:
          CYPRESS_baseUrl: http://localhost:3000
