name: Cypress E2E on PR

on:
  pull_request:
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout frontend repo
        uses: actions/checkout@v3
        
      - name: Checkout backend repo
        uses: actions/checkout@v3
        with:
          repository: fac-31/Pro0428-MindPalaceBackend
          path: backend
          
      - name: Generate backend .env file
        run: |
          echo "OPENAI_KEY=${{ secrets.OPENAI_KEY }}" >> backend/.env
          echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> backend/.env
          echo "PORT=5000" >> backend/.env

      - name: Build frontend dependencies
        run: npm ci

      - name: Build & start full stack using docker-compose
        run: docker compose -f docker-compose.ci.yml up -d --build

      - name: List running containers and ports
        run: |
          echo "=== Running containers ==="
          docker ps
          echo "=== Docker container port mappings ==="
          docker port $(docker ps -qf name=backend)

      - name: Show logs of backend container (last 20 lines)
        run: docker logs --tail 20 $(docker ps -qf name=backend) || echo "Backend container not found or not running"

      - name: Wait for backend port 5000 to be open on localhost (with retries)
        run: |
          for i in {1..20}; do
            echo "Checking if backend port 5000 is open on localhost (attempt $i)..."
            if nc -z localhost 5000; then
              echo "Port 5000 is open on localhost"
              # Try to get a response from backend endpoint
              if curl -f http://localhost:5000; then
                echo "Backend responded successfully!"
                exit 0
              else
                echo "Backend not responding yet"
              fi
            else
              echo "Port 5000 not open yet"
            fi
            sleep 3
          done
          echo "Backend did not become ready in time"
          exit 1

      - name: Wait for frontend port 3000 to be open on localhost (with retries)
        run: |
          for i in {1..20}; do
            echo "Checking if frontend port 3000 is open on localhost (attempt $i)..."
            if nc -z localhost 3000; then
              echo "Port 3000 is open on localhost"
              if curl -f http://localhost:3000; then
                echo "Frontend responded successfully!"
                exit 0
              else
                echo "Frontend not responding yet"
              fi
            else
              echo "Port 3000 not open yet"
            fi
            sleep 3
          done
          echo "Frontend did not become ready in time"
          exit 1

      - name: Run Cypress tests
        run: npx cypress run
        env:
          CYPRESS_baseUrl: http://localhost:3000
