name: Cypress E2E on PR
on:
  pull_request:
  workflow_dispatch:
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout frontend repo
        uses: actions/checkout@v3
        
      - name: Checkout backend repo
        uses: actions/checkout@v3
        with:
          repository: fac-31/Pro0428-MindPalaceBackend
          path: backend
          
      - name: Generate backend .env file
        run: |
          cd backend
          echo OPENAI_KEY=${{ secrets.OPENAI_KEY }} >> .env
          echo SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }} >> .env
          echo PORT=5000 >> .env
          
      - name: Start backend
        run: |
          cd backend
          docker compose up -d
          
      - name: Wait for backend
        run: sleep 10
        
      - name: Install frontend dependencies
        run: npm ci
        
      - name: Run Cypress tests
        run: npx cypress run
        env:
          CYPRESS_baseUrl: http://localhost:5000
